{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cubyz-server.fullname" . }}
  labels:
    {{- include "cubyz-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cubyz-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressCIDRs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: UDP
          port: {{ .Values.containerPort }}
{{- end }}
